[tool.aerich]
tortoise_orm = "migrations.tortoise_config.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.poetry]
name = "sahasrahbot"
version = "0.1.0"
description = ""
authors = ["Thomas Prescott <tcprescott@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
quart = "*"
Quart-Discord = ">=2.1.4"
aerich = ">=0.5.5"
aioboto3 = ">=8.0.5"
aiocache = ">=0.11.1"
aiofiles = ">=0.4.0"
aiohttp = "*"
aiomysql = ">=0.0.20"
discord-sentry-reporting = "*"
emoji = "*"
dataclasses-json = "*"
gspread-asyncio = "*"
PyYAML = "*"
python-dotenv = "*"
html2markdown = "*"
urlextract = "*"
oauth2client = "*"
google-api-python-client = "*"
html5lib = "*"
shortuuid = "*"
python-slugify = "*"
pyz3r = "*"
isodate = "*"
"discord.py" = "*"
jishaku = "*"
pyrankvote = "*"
racetime-bot = {url = "https://github.com/tcprescott/racetime-bot/archive/1e74910b1520c4be31a84253dabeda264fe54841.zip"}


[tool.poetry.group.dev.dependencies]
pycodestyle = "*"
pylint = "*"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
